apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archiver
  template:
    metadata:
      labels:
        app: archiver
    spec:
      containers:
        - name: archiver
          image: abvc/archiver:latest
