name: CI

on: [push]

jobs:
  check-my-app:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: pip install requests

        - name: Set up Docker
          run: docker compose up -d

        - name: Run Integration test
          run: python3 tester.py

